### PR TITLE
add Script overload to Module

### LINKED ISSUE #205: [BUG] missing module constructor
According to the source code i should be able to create a `Module` with a pre-parsed `Script`, but the published `NiL.JS` version does not contain that constructor.

https://github.com/nilproject/NiL.JS/blob/8f95c548f05644d498d318980c5545139796914e/NiL.JS/Module.cs#L153

Im using latest version from [nuget](https://www.nuget.org/packages/NiL.JS.NetCore).

### PR DESCRIPTION
**Pull request by viceice**
This will allow to create modules in a fast way with pre-parsed scripts
for netstandard.

this is related to #197 and fixes #205

### CODE REVIEW

**Comment by rmja** [comment]
Isn't this already included in #197 which is merged. I can see the sample overload here: https://github.com/nilproject/NiL.JS/blob/develop/NiL.JS/Module.cs#L153-L167

**Comment by viceice** [comment]
No, it is only added for net45  and missing on netcore.

https://github.com/nilproject/NiL.JS/blob/ca26a334b9edc31973c88fc0c3397cfc25f53686/NiL.JS.NetCore/Module.cs#L140-L154

**Comment by rmja** [comment]
Ahh crap, my fault.

**Comment by viceice** [comment]
np, hopefully this is fixed soon, so i can start caching my `Script` objects.

**Comment by nilproject** [comment]
The best argument of necessity of rework project structure.
So, from afe285b392f2abd238a4be86c990b0da7a7c05bf this pr is outdated

**Pull request closed without merging**
